PORT: autoconf; add ESCDELAY variable check to autoconf scripts

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4421,6 +4421,68 @@ _ACEOF
 
      fi
    fi
+   { echo "$as_me:$LINENO: checking for ESCDELAY variable" >&5
+echo $ECHO_N "checking for ESCDELAY variable... $ECHO_C" >&6; }
+if test "${mc_cv_ncurses_escdelay+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+			extern int ESCDELAY;
+			ESCDELAY = 0;
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  mc_cv_ncurses_escdelay=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	mc_cv_ncurses_escdelay=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+
+fi
+{ echo "$as_me:$LINENO: result: $mc_cv_ncurses_escdelay" >&5
+echo "${ECHO_T}$mc_cv_ncurses_escdelay" >&6; }
+    if test "$mc_cv_ncurses_escdelay" = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_ESCDELAY 1
+_ACEOF
+
+    fi
    if test ! "$CURSES_LIB" ; then
        LIBS="$mp_save_LIBS"
    fi
